OPENAI_MODEL = "gpt-3.5-turbo"

NEO4J_LOCAL = "bolt://localhost:7687"
NEO4J_LOCAL_USER = "neo4j"
NEO4J_LOCAL_PASSWORD = "j4oenj4oen"

NEO4J_SANDBOX = "bolt://18.207.217.56:7687"
NEO4J_SANDBOX_USER = "neo4j"
NEO4J_SANDBOX_PASSWORD = "tackle-halyards-halt"
